default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: landing3
production:
  <<: *default
  database: landing3